### ISSUE TITLE
错误：AccessToken is invalid. 

### ISSUE THREAD

**Issue by xuemingfeng** [zuozishi/AliyunDriveAPI#5]
场景描述：
1. 启动程序，可正常上传文件
2. 大约2小时后，再次上传文件失败（期间程序不关闭）
3. 错误信息：AccessToken is invalid. AccessTokenExpired

原因分析：
1. AccessToken过期

排查文件 AliyunDriveApiClient.File.cs：
1. 在 `UploadFileAsync()` 方法中未执行 `await PrepareTokenAsync();` 重新获取 Token
2. 将 `await PrepareTokenAsync();` 添加到方法后，错误重现，未能解决

继续排查 AliyunDriveApiClient.cs：
````
    private bool IsTokenExpire()
        => _tokenExpireTime == null || _tokenExpireTime.Value > DateTime.UtcNow;
````
1. `_tokenExpireTime.Value` 值为本机时间，非UTC时间
2. 时间会是 `'2022/10/19 11:10:42' > '2022/10/19 1:10:41'`
3. 值在10小时内永远是 false，而 AccessToken 有效值只有2小时
4. 2小时后，`IsTokenExpire()` 返回仍然是 false，而 AccessToken 已经过期

更新代码：
````
    private bool IsTokenExpire()
        => _tokenExpireTime == null || _tokenExpireTime.Value <= DateTime.Now; 
````

目前观察运行正确。

**Comment by zuozishi** [comment]
#6 merged
